config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get  '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  get   '/logout', to: "sessions#destroy"

  resources :users, only: [:new, :create, :show] do
    resources :ideas, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  end

  namespace :admin do
    resources :categories
  end

  namespace :admin do
    resources :pictures, only: [:new, :create, :index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :ideas
end

app/models/idea.rb
class Idea < ApplicationRecord
  validates :title, presence: true, uniqueness: true

  belongs_to :category
  belongs_to :user

  has_many :uploads
  has_many :pictures, through: :uploads
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :image, ImageUploader

  has_many :uploads
  has_many :ideas, through: :uploads
end

app/models/upload.rb
class Upload < ApplicationRecord
  belongs_to :picture
  belongs_to :idea
end

app/models/user.rb
class User < ApplicationRecord
  validates :user_name, presence: true, uniqueness: true

  has_secure_password
  has_many :ideas

  enum role: ["default", "admin"]
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  def require_admin
    render file: "/public/404" unless current_admin?
  end

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  before_action :set_category, only: [:show, :edit, :destroy]

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "You've successfully created a new category!"

      redirect_to admin_category_path(@category)
    else
      render :new
    end
  end

  def edit

  end

  def update
    @category = Category.update(category_params)

    redirect_to admin_category_path(@category)
  end

  def destroy
    @category.destroy

    redirect_to admin_categories_path
  end


  private

    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/admin/pictures_controller.rb
class Admin::PicturesController < ApplicationController

  def index
    @pictures = Picture.order("created_at DESC")
  end

  def new
    @picture = Picture.new
  end

  def create
    @picture = Picture.new(picture_params)
    if @picture.save
      flash[:success] = "You've uploaded a Picture"

      redirect_to admin_pictures_path
    else
      render :new
    end
  end


  private

    def picture_params
      params.require(:picture).permit(:title, :body, :image)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin?
  end

  def render_404
    render file: "#{Rails.root}/public/404", layout: false, status: :not_found
  end


  def logged_in?
    if current_user.nil?
      render_404
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def new
    @category = Category.new
  end

  def show

  end

  def create
    category = Category.new(category_params)
    if category.save
      flash[:success] = "You've created a new category"

      redirect_to category_path(category)
    else
      redirect :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    category = Category.update(category_params)

    redirect_to categories_path
  end

  def destroy
    category = Category.find(params[:id])
    category.destroy

    redirect_to categories_path
  end


  private




  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_user
  before_action :categories_all
  before_action :logged_in?


  def index
    if current_user.id == session[:user_id]
      @ideas = @user.ideas.all
    else
      render_404
    end
  end

  def show
    @idea = @user.ideas.find(params[:id])
  end

  def new
    @idea = @user.ideas.new
    @pictures = Picture.all
  end

  def create
    @idea = @user.ideas.new(idea_params)
    if @idea.save
      flash[:success] = "You've created your new Idea!"
      Upload.create(picture_id: params[:picture_ids][0].to_i, idea_id: @idea.id)
      redirect_to user_idea_path(@user, @idea)
    else
      render :new
    end
  end

  def edit
    @idea = Idea.find(params[:id])
    @pictures = Picture.all
  end

  def update
    @idea = @user.ideas.update(idea_params)

    Upload.create(picture_id: params[:picture_ids][0].to_i, idea_id: @idea.last.id)
    redirect_to user_idea_path(@user, @idea)
    
  end

  def destroy
    @idea = @user.ideas.find(params[:id])
    @idea.destroy

    redirect_to user_ideas_path(@user)
  end



  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def categories_all
    @categories = Category.all
  end

  def idea_params
    params.require(:idea).permit(:title, :category_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(user_name: params[:user_name])
    # byebug
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id

      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in?, only: [:show]

  def show
    if current_user.id == session[:user_id]
      @user = User.find(params[:id])
    else
      render_404
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(users_params)
    if @user.save
      session[:user_id] = @user.id

      redirect_to user_path(@user)
    else
      render :new
    end
  end

  private

    def users_params
      params.require(:user).permit(:user_name, :password)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, @category] do |f|%>

<%= f.text_field :name, placeholder: "Name" %>

<%= f.submit "Submit" %>
<% end %>

app/views/admin/categories/edit.html.erb
<div class="user-show">
  <%= render partial: "form" %>
</div>

app/views/admin/categories/index.html.erb
<div class="category-index">
  All Categories
  <section>
    <% @categories.each do |category| %>
    <%= category.name %>
    <%= link_to "Delete Category", { action: :destroy, id: category.id }, method: :delete, data: "Please confirm delete" %>
    <%= link_to "Edit Category", edit_admin_category_path(category)%>
    <% end %>
    <%= link_to "Create Category", new_admin_category_path %>
  </section>
</div>

app/views/admin/categories/new.html.erb
<div class="user-show">
  Create a Category
</div>

<div class="category-form">
  <%= render partial: "form" %>
</div>

app/views/admin/categories/show.html.erb
<div class="category-show">
  <%= @category.name %>
  <%= link_to "Category Index", admin_categories_path %>
  <%= link_to "Delete Category", { action: :destroy, id: @category.id }, method: :delete, data: "Please confirm delete" %>
</div>

app/views/admin/pictures/_form.html.erb
<%= form_for [:admin, @picture] do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div>
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <%= f.submit %>
<% end %>

app/views/admin/pictures/index.html.erb
<div class="picture-index">
  <h1>Pictures</h1>

  <%= link_to 'Add Picture', new_admin_picture_path %>

  <% @pictures.each do |picture| %>
  <%= picture.title %>
  <%= image_tag(picture.image.url, alt: 'Image') if picture.image? %>
  <%= picture.body %>
  <% end %>
</div>

app/views/admin/pictures/new.html.erb
<div class="user-show">
<h1>Add post</h1>
</div>
<%= render 'form', picture: @picture %>

app/views/admin/pictures/show.html.erb
<%= link_to 'All Pictures', admin_pictures_path %>
<h1><%= @picture.title %></h1>

<%= link_to(image_tag(@picture.image.thumb.url, alt: 'Image'), @picture.image.url, target: '_blank') if @picture.image? %>


<p><%= @picture.body %></p>

app/views/ideas/_form.html.erb
<%= form_for [@user, @idea] do |f| %>

Title Of Idea:  <%= f.text_field  :title, placeholder: "Insert Title" %>
<br>
Title Category:  <%= f.collection_select :category_id, Category.order(:name), :id, :name, include_blank: true%>

<% @pictures.each do |picture| %>
<div class="picture-card-<%=picture.id%>">
  <%= image_tag(picture.image.url, alt: 'Image', height: 150, width: 150) if picture.image? %>
  <%= check_box_tag 'picture_ids[]', picture.id -%>
</div>
<% end %>

<%= f.submit "Create Idea", :class => "create_idea_button"%>
<% end %>

app/views/ideas/edit.html.erb
<div class="user-show">

<h1>Edit your Idea!</h1>
</div>
<br>
<br>
<%= form_for [@user, @idea] do |f| %>

<%= f.text_field  :title, placeholder: "#{@idea.title}" %>
<%= f.collection_select :category_id, Category.order(:name), :id, :name, include_blank: true%>
<br>
<% @pictures.each do |picture| %>
<div class="picture-card-<%=picture.id%>">
  <%= image_tag(picture.image.url, alt: 'Image', height: 150, width: 150) if picture.image? %>
  <%= check_box_tag 'picture_ids[]', picture.id -%>a
</div>
<% end %>
<%= f.submit "Edit Idea", :class => "create_idea_button"%>
<% end %>

app/views/ideas/index.html.erb
<div class="idea-index">
  <div class="user-show">

  <h1>All Ideas for <%= current_user.user_name %></h1>
  </div>
  <div class="create-idea-button">
    <%= link_to "Create New Idea", new_user_idea_path(current_user) %>
  </div>
    <% @ideas.each do |idea| %>
  <div class="index-ideas">
  Idea Name: <%= idea.title %>
    <br>
  Idea Category: <%= idea.category.name %>
    <br>
    <br>
    <% idea.pictures.each do |picture| %>
      <%= image_tag(picture.image.url, alt: 'Image', height: 150, width: 150) if picture.image? %>
    <% end %>
    <div class="delete-button">
      <%= link_to "Delete", { action: :destroy, id: idea.id }, method: :delete, data: "Please confirm delete" %>
      <%= link_to "Edit", edit_user_idea_path(current_user, idea)%>
    </div>

    <% end %>
    </div>
</div>

app/views/ideas/new.html.erb
<div class="user-show">
<h1>Create your Idea</h1>
</div>
<%= render partial: "form" %>

app/views/ideas/root.html.erb
<div class="main-root-display">
  <section>
    Welcome to Idea Box
  </section>
</div>

app/views/ideas/show.html.erb
<h1>Idea Details</h1>
<%= @idea.title %>
<%= @idea.category.name %>
<% @idea.pictures.each do |picture| %>
  <%= image_tag(picture.image.url, alt: 'Image', height: 150, width: 150) if picture.image? %>
<% end %>
<%= link_to "Change Your Idea", edit_user_idea_path(@user, @idea) %>
<%= link_to "Delete", { action: :destroy, id: @idea.id }, method: :delete, data: "Please confirm delete" %>
<%= link_to "Go Back to your Ideas", user_ideas_path(@user) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IdeaBox</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" type="text/scss" href="/stylesheets/reset.scss">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class= "nav-bar">
      <%= link_to image_tag("logo.png", width:120, height:120), root_path %>
      <% if session[:user_id].nil? %>
        <div class="nav-links" >
          <%= link_to "Create Account", new_user_path %>
        </div>
        <div class="nav-links" >
          <%= link_to "Login", login_path %>
        </div>
      <% else %>
        <div class="nav-links" >
          <%= link_to "Log out", logout_path %>
        </div>
      <% end %>
    </nav>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: name %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<div class="user_form">
  Please create an IdeaBox account!
</div>
  <%= form_for @user do |f| %>
  <div class="input-fields">
    <%= f.text_field :user_name, placeholder: "Username" %>
  </div>
    <div class="input-fields">
    <%= f.password_field :password, placeholder: "Password"%>
  </div>
    <div class="submit-button">
    <%= f.submit "Create New User"%>
  </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="user-show">
Welcome, <%= current_user.user_name %>!
</div>
<div class="create-idea-button">
  <%= link_to "Create New Idea", new_user_idea_path(current_user) %>
</div>
<div class="review-ideas">
  <%= link_to "Review Your Ideas", user_ideas_path(current_user) %>
</div>
<% if current_user.admin? %>
<div class="create-category">
  <%= link_to "Create Category", new_admin_category_path %>
</div>
<div class="create-pic">
  <%= link_to "Create Picture", new_admin_picture_path %>
</div>
<% end %>

app/views/welcome/index.html.erb
<section class= "dashboard">
  Generate, Organize, and Track Ideas
</section>